<?php

namespace Tests\Unit\Models;

use App\Models\Order;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class OrderTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_contains_valid_fillable_properties()
    {
        $order = new Order();
        $this->assertEquals([
            'user_id',
            'total_quantity',
            'total_price',
            'status',
        ], $order->getFillable());
    }

    public function test_order_detail_relation()
    {
        $order = new Order();
        $relation = $order->orderDetails();
        $this->assertInstanceOf(HasMany::class, $relation);
        $this->assertEquals('order_id', $relation->getForeignKeyName());
        $this->assertEquals('id', $relation->getLocalKeyName());
    }

    public function test_user_relation()
    {
        $order = new Order();
        $relation = $order->user();
        $this->assertInstanceOf(BelongsTo::class, $relation);
        $this->assertEquals('user_id', $relation->getForeignKeyName());
        $this->assertEquals('id', $relation->getOwnerKeyName());
    }

    public function test_table_name()
    {
        $order = new Order();
        $this->assertEquals('orders', $order->getTable());
    }
}
