<?php

namespace Tests\Unit\Models;

use App\Models\Permission;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class PermissionTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_contains_valid_fillable_properties()
    {
        $permission = new Permission();
        $this->assertEquals([
            'name',
        ], $permission->getFillable());
    }

    public function test_role_relation()
    {
        $permission = new Permission();
        $relation = $permission->roles();
        $this->assertInstanceOf(BelongsToMany::class, $relation);
        $this->assertEquals('permission_id', $relation->getForeignPivotKeyName());
        $this->assertEquals('role_id', $relation->getRelatedPivotKeyName());
    }

    public function test_table_name()
    {
        $permission = new Permission();
        $this->assertEquals('permissions', $permission->getTable());
    }
}
