<?php

namespace Tests\Unit\Models;

use App\Models\Role;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class RoleTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_contains_valid_fillable_properties()
    {
        $role = new Role();
        $this->assertEquals([
            'name',
            'slug',
        ], $role->getFillable());
    }

    public function test_permission_relation()
    {
        $role = new Role();
        $relation = $role->permissions();
        $this->assertInstanceOf(BelongsToMany::class, $relation);
        $this->assertEquals('role_id', $relation->getForeignPivotKeyName());
        $this->assertEquals('permission_id', $relation->getRelatedPivotKeyName());
    }

    public function test_user_relation()
    {
        $role = new Role();
        $relation = $role->users();
        $this->assertInstanceOf(HasMany::class, $relation);
        $this->assertEquals('role_id', $relation->getForeignKeyName());
        $this->assertEquals('id', $relation->getLocalKeyName());
    }

    public function test_table_name()
    {
        $role = new Role();
        $this->assertEquals('roles', $role->getTable());
    }
}
