<?php

namespace Tests\Unit\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserTest extends TestCase
{
    /**
     * A basic unit test example.
     *
     * @return void
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_contains_valid_fillable_properties()
    {
        $user = new User();
        $this->assertEquals([
            'name',
            'email',
            'password',
        ], $user->getFillable());
    }

    public function test_order_relation()
    {
        $user = new User();
        $relation = $user->orders();
        $this->assertInstanceOf(HasMany::class, $relation);
        $this->assertEquals('user_id', $relation->getForeignKeyName());
        $this->assertEquals('id', $relation->getLocalKeyName());
    }

    public function test_rate_relation()
    {
        $user = new User();
        $relation = $user->rates();
        $this->assertInstanceOf(HasMany::class, $relation);
        $this->assertEquals('user_id', $relation->getForeignKeyName());
        $this->assertEquals('id', $relation->getLocalKeyName());
    }

    public function test_activity_relation()
    {
        $user = new User();
        $relation = $user->activities();
        $this->assertInstanceOf(HasMany::class, $relation);
        $this->assertEquals('user_id', $relation->getForeignKeyName());
        $this->assertEquals('id', $relation->getLocalKeyName());
    }

    public function test_suggest_relation()
    {
        $user = new User();
        $relation = $user->suggests();
        $this->assertInstanceOf(HasMany::class, $relation);
        $this->assertEquals('user_id', $relation->getForeignKeyName());
        $this->assertEquals('id', $relation->getLocalKeyName());
    }

    public function test_role_relation()
    {
        $user = new User();
        $relation = $user->role();
        $this->assertInstanceOf(BelongsTo::class, $relation);
        $this->assertEquals('role_id', $relation->getForeignKeyName());
        $this->assertEquals('id', $relation->getOwnerKeyName());
    }

    public function test_product_relation()
    {
        $user = new User();
        $relation = $user->products();
        $this->assertInstanceOf(BelongsToMany::class, $relation);
        $this->assertEquals('product_user.user_id', $relation->getQualifiedForeignPivotKeyName());
        $this->assertEquals('product_user.product_id', $relation->getQualifiedRelatedPivotKeyName());
    }

    public function test_table_name()
    {
        $user = new User();
        $this->assertEquals('users', $user->getTable());
    }
}
